{{- if .Values.config.secretEnvs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "faucet-app.common.fullname" . }}-secret-env
  labels:
    {{- include "faucet-app.common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
{{- range $key, $value := .Values.config.secretEnvs  }}
  {{- $key | nindent 2 }}: {{ $value | print | b64enc }}
{{- end }}
{{- end }}
