config:
  args: ["./faucet-server"]
  logLevel: debug
  clearnodeWsUrl: wss://canarynet.yellow.com/ws
  token:
    symbol: ytest.usd
    tipAmount: 0.1
  minTransferCount: 5
  envSecret: ""
  extraEnvs: {}

image:
  repository: ghcr.io/erc7824/faucet-app/server
  tag: 25f6448

imagePullSecret: ghcr-pull

service:
  http:
    enabled: true
    port: 8080
    path: /faucet(/|$)(.*)

metrics:
  enabled: false
  podmonitoring:
    enabled: false
  port: 4242
  endpoint: "/metrics"

resources:
  limits:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 100Mi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 100Mi

autoscaling:
  enabled: false

networking:
  externalHostname: canarynet.yellow.com
  tlsClusterIssuer: zerossl-prod
  gateway:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    tls:
      enabled: true
